 # For details on how this file works refer to:
 #   - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  #  - Check for updates once a week
  #  - Group all updates into a single PR
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-actions:
        patterns: [ "*" ]
    
  # Maintain dependencies for TypeScript and JavaScript
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  # Maintain dependencies for Java
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily

  # Maintain dependencies for Objective-C
  - package-ecosystem: cocoapods
    directory: /
    schedule:
      interval: daily

  # Maintain dependencies for Shell scripts
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily

  # Maintain dependencies for Ruby
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily